export const data = [
["Germany","Aachen","Westfälische Technische Hochschule Aachen (D  AACHEN01)","Si","Si","No",12],
["Germany","Berlin","Technische Universität Berlin (D  BERLIN02)","Si","Si","No",2],
["Germany","Braunschweig","Technische Universität Carolo-Wilhelmina zu Braunschweig (DBRAUNSC01)","Si","Si","No",1],
["Germany","Clausthal-Zellerfeld","Technische Universität Clausthal (D  CLAUSTH01)","Si","Si","No",1],
["Germany","Darmstadt","Technische Universität Darmstadt (D  DARMSTA01)","Si","Si","No",10],
["Germany","Dresden","Technische Universität Dresden (D  DRESDEN02)","Si","Si","No",2],
["Germany","Hamburg","Technische Universität Hamburg-Harburg (D  HAMBURG03)","Si","Si","No",5],
["Germany","Heilbronn","Hochschule Heilbronn (D  HEILBRO01)","Si","Si","No",2],
["Germany","Kaiserslautern","Technische Universität Kaiserslautern (D  KAISERS01)","Si","Si","No",2],
["Germany","Kaiserslautern","Technische Universität Kaiserslautern* (D  KAISERS01)","Si","Si","No",2],
["Germany","Karlsruhe","Karlsruhe Institute für Technologie* (DKARLSRU01)","Si","Si","No",2],
["Germany","Karlsruhe","Karlsruher Institut für Technologie (D  KARLSRU01)","Si","Si","No",4],
["Germany","Munich","Technische Universität München (D  MUNCHEN02)","Si","Si","No",25],
["Germany","Stuttgart","Universität Stuttgart (D  STUTTGA01)","Si","Si","No",2],
["Austria","Graz","Technische Universität Graz (A  GRAZ02)","Si","Si","No",2],
["Austria","Innsbruck","MCI - Management Center Innsbruck (A INNSBRU08)","Si","Si","No",3],
["Austria","Leoben","Montanuniversität Leoben (A  LEOBEN01)","Si","Si","Si",2],
["Austria","Leoben","#N/A","Si","Si","Si",1],
["Austria","Vienna","Technische Universität Wien (A  WIEN02)","Si","Si","No",4],
["Belgium","Brussels","Université Libre de Bruxelles (B  BRUXEL04)","Si","Si","No",4],
["Belgium","Gent","Universiteit Gent (B  GENT01)","Si","Si","No",5],
["Belgium","Leuven","Katholieke Universiteit Leuven (B  LEUVEN01)","Si","Si","No",6],
["Belgium","Liège","Université de Liège (B  LIEGE01)","Si","Si","No",2],
["Belgium","Louvain-la-Neuve","Université Catholique de Louvain (B  LOUVAIN01)","Si","Si","No",2],
["Bulgaria","Sofia","Visshe Transportno Uchilishte 'TodorKableshkov'(BG SOFIA22)","Si","Si","No",2],
["Denmark","Aalborg","Aalborg Universitet (DK ALBORG01)","Si","Si","No",2],
["Denmark","Copenhagen","Danmarks Tekniske Universitet (DK LYNGBY01)","Si","Si","No",2],
["Slovakia","Bratislava","Slovenská Technická Univerzita V Bratislave (STU) (SK BRATISL01)","Si","Si","No",1],
["Slovenia","Ljubljana","Univerza v Ljubljani (SI LJUBLJA01)","Si","Si","Si",2],
["Slovenia","Ljubljana","Univerza v Ljubljani* (SI LJUBLJA01)","No","Si","No",2],
["Finland","Otaniemi","AALTO UNIVERSITY, SCHOOL OF ART, DESING AND ARCHITECTURE(SF ESPOO12)","Si","Si","No",4],
["Finland","Lappeenranta","Lappeenrannan Teknillinen Yliopisto (SF LAPPEEN01)","Si","Si","No",2],
["Finland","Tampere","Tampereen Teknillinen Yliopisto (SF TAMPERE02)","Si","Si","No",3],
["France","Alès","Ecole Nationale Superieure des Techniques Industrielles et desMines d'Ales (F  ALES02)","Si","Si","No",3],
["France","Bayonne","Estia- Ecole d Ingenieurs (F  BAYONNE07)","Si","Si","No",2],
["France","Belfort","Université de Technologie de Belfort-Montbeliard (F  BELFORT06)","Si","Si","No",4],
["France","Blois","INSA Centre Val de Loire (F  BLOIS13)","Si","Si","Si",2],
["France","Bourges","INSA Centre Val de Loire (F  BLOIS13)","Si","Si","Si",2],
["France","Brest","Ecole Nationale d'Ingénieurs de Brest (ENIB) (F  BREST07)","Si","Si","No",2],
["France","Cergy","Ecole Nationale Superieure de l'Electronique et de ses Application (FCERGY01)","Si","Si","Si",2],
["France","Clermont-Ferrand","SIGMA Clermont (F  AUBIERE04)","Si","Si","No",2],
["France","Compiègne","Université de Technologie de Compiegne (F  COMPIEG01)","Si","Si","No",1],
["France","Dijon","Université de Bourgogne - Dijon (F  DIJON01)","Si","Si","No",5],
["France","Douai","Ecole des Mines de Douai (F  DOUAI02)","Si","Si","No",4],
["France","Grenoble","I.N.P. de Grenoble (F  GRENOBL22)","Si","Si","No",2],
["France","Grenoble","I.N.P. de Grenoble * (F  GRENOBL22)","Si","Si","No",9],
["France","La Rochelle","Ecole d'Ingénieurs en Génie des Systèmes Industriels (EIGSI) (F  LA-ROCH09)","Si","Si","No",2],
["France","Lille","Ecole Centrale de Lille (F  LILLE14)","Si","Si","No",3],
["France","Lille","Université Catholique de Lille (F  LILLE11)","Si","Si","No",2],
["France","Lille","Université des Sciences et Technologies de Lille (F  LILLE01)","Si","Si","No",8],
["France","Lyon","École Catholique d'Arts et Métiers de Lyon (F LYON13)","Si","Si","Si",2],
["France","Lyon","Ecole Centrale de Lyon (F  LYON11)","Si","Si","No",10],
["France","Lyon","Ecole Superieure de Chimie Physique Electronique de Lyon (FLYON15)","Si","Si","No",4],
["France","Lyon","Institut National des Sciences Appliquees de Lyon (F  LYON12)","Si","Si","No",13],
["France","Marseille","Ecole Centrale Marseille (F  MARSEIL11)","Si","Si","No",6],
["France","Nancy","Université de Lorraine (F NANCY43)","Si","Si","No",3],
["France","Nantes","Ecole Centrale de Nantes (F  NANTES07)","Si","Si","No",6],
["France","Nantes","Ecole des Mines de Nantes (F  NANTES37)","Si","Si","No",2],
["France","Orléans","Université d'Orléans (F  ORLEANS01)","Si","Si","No",3],
["France","Palaiseau","École Polytechnique (F  PALAISE01)","Si","Si","Si",3],
["France","Paris","École des Ponts Paris Tech (F  PARIS085)","Si","Si","No",4],
["France","Paris","Ecole Nationale Superieure d'Arts et Metiers (F  PARIS062)","Si","Si","No",8],
["France","Paris","École Nationale Supérieure de Chimie de Paris (F PARIS063)","Si","Si","No",2],
["France","Paris","Ecole Nationale Superieure de Techniques Avancees (F  PARIS080)","Si","Si","No",8],
["France","Paris","Ecole Nationale Superieure des Mines de Paris (F  PARIS081)","Si","Si","Si",2],
["France","Paris","Université de Paris-Sud (Paris XI) (F  PARIS011)","Si","Si","No",3],
["France","Rennes","Institut National des Sciences Appliquees de Rennes (F  RENNES10)","Si","Si","Si",2],
["France","Rouen","Institut National des Sciences Appliquees de Rouen (F  ROUEN06)","Si","Si","No",2],
["France","Rouen","Institut National des Sciences Appliquees de Rouen* (F  ROUEN06)","Si","Si","No",2],
["France","Paris","EPF Ecole d'Ingenieurs (F  SCEAUX01)","Si","Si","No",1],
["France","Saint-Étienne","Ecole Nationale d'Ingenieurs de Saint-Etienne (F  ST-ETIE05)","Si","Si","No",4],
["France","Saint-Étienne","Ecole Nationale Superieure des Mines de Saint-Etienne (F  ST-ETIE06)","Si","Si","No",3],
["France","Strasbourg","Université de Strasbourg (F  STRASBO48)","Si","Si","No",4],
["France","Tarbes","Ecole Nationale d'Ingenieurs de Tarbes (F  TARBES03)","Si","Si","No",2],
["France","Toulouse","Ecole Nationale Superieure de l'Aeronautique et de l'Espace (FTOULOUS16)","Si","Si","No",2],
["France","Toulouse","Institut National des Sciences Appliquees de Toulouse (FTOULOUS14)","Si","Si","No",2],
["France","Toulouse","Institut National Polytechnique de Toulouse (F  TOULOUS28)","Si","Si","No",7],
["France","Troyes","Université de Technologie de Troyes (F  TROYES08)","Si","Si","No",1],
["France","Valenciennes","Université de Valenciennes et du Hainaut-Cambresis (F  VALENCI01)","Si","Si","No",1],
["Hungary","Budapest","Budapesti Muszaki és Gazdaságtudományi Egyetem (HUBUDAPES02)","Si","Si","No",2],
["Ireland","Dublin","Dublin Institute of Technology (IRL DUBLIN27)","Si","No","No",2],
["Italy","Ancona","Università Politecnica delle Marche (I  ANCONA01)","Si","Si","No",2],
["Italy","Bari","Politecnico di Bari (I  BARI05)","Si","Si","No",2],
["Italy","Bologna","Università di Bologna Alma Mater Studiorum (I  BOLOGNA01)","Si","Si","No",3],
["Italy","Brescia","Università degli Studi di Brescia (I  BRESCIA01)","Si","Si","No",2],
["Italy","Cassino","Università degli Studi di Cassino (I  CASSINO01)","Si","Si","Si",1],
["Italy","Cassino","Università degli Studi di Cassino * (I  CASSINO01)","Si","Si","No",2],
["Italy","Florence","Università degli Studi di Firenze (I  FIRENZE01)","Si","Si","No",2],
["Italy","Genoa","Università degli Studi di Genova (I  GENOVA01)","No","Si","No",2],
["Italy","Genoa","Università degli Studi di Genova* (I  GENOVA01)","Si","Si","No",2],
["Italy","Messina","Università degli Studi di Messina (I  MESSINA01)","Si","Si","No",2],
["Italy","Messina","Università degli Studi di Messina* (I  MESSINA01)","Si","Si","No",1],
["Italy","Milan","Politecnico di Milano (I  MILANO02)","Si","Si","No",13],
["Italy","Naples","Università degli Studi di Napoli Federico II (I  NAPOLI01)","Si","Si","No",4],
["Italy","Parma","Università degli Studi di Parma (I  PARMA01)","Si","Si","No",2],
["Italy","Pisa","Università degli Studi di Pisa (I  PISA01)","Si","Si","No",2],
["Italy","Rome","Università degli Studi di Roma 'Tor Vergata' (I  ROMA02)","Si","Si","No",4],
["Italy","Rome","Università degli Studi Roma Tre (I  ROMA16)","Si","Si","No",1],
["Italy","Rome","Universita deglistudi Guglielmo Marconi (I ROMA21)","Si","Si","No",2],
["Italy","Turin","Politecnico di Torino (I  TORINO02)","Si","Si","Si",13],
["Italy","Trento","Università degli Studi di Trento (I  TRENTO01)","Si","Si","No",2],
["Norway","Trondheim","Norges Teknisk-Naturvitenskapelige Universitet (N  TRONDHE01)","Si","Si","No",3],
["Netherlands","Delft","Technische Universiteit Delft (NL DELFT01)","Si","Si","Si",3],
["Netherlands","Delft","Technische Universiteit Delft* (NL DELFT01)","No","Si","No",1],
["Netherlands","Eindhoven","Technische Universiteit Eindhoven (NL EINDHOV17)","Si","Si","No",1],
["Poland","Gdańsk","Politechnika Gdanska (PL GDANSK 02)","Si","Si","No",1],
["Poland","Łódź","Lodz University of Technology (PL LODZ02)","Si","Si","No",3],
["Poland","Poznań","Politechnika Poznanska (PL POZNAN02)","Si","Si","No",6],
["Poland","Warszawa","Politechnika Warszawska (PL WARSZAW02)","Si","Si","No",2],
["Poland","Warszawa","Politechnika Warszawska * (PL  WARSZAW02)","Si","Si","No",2],
["Poland","Warszawa","Wojskowa Akademia Techniczna (PL WARSZAW33)","Si","Si","Si",4],
["Poland","Wrocław","Politechnika Wroclwskca/Wroclaw University of Thechnology (PL WROCLAW 02)","Si","Si","Si",4],
["Portugal","Braga","Universidade do Minho (P  BRAGA01)","Si","Si","Si",2],
["Portugal","Lisbon","Universidade de Lisboa (P  LISBOA109)","Si","Si","No",2],
["Portugal","Lisbon","Universidade Nova de Lisboa (P  LISBOA03)","Si","Si","Si",2],
["Portugal","Lisbon","Universidade Nova de Lisboa* (P  LISBOA03)","Si","Si","No",3],
["Portugal","Porto","Instituto Politécnico do Porto (P  PORTO05)","Si","Si","No",2],
["Portugal","Porto","Universidade do Porto (P  PORTO02)","Si","Si","No",1],
["Portugal","Setúbal","Instituto Politécnico de Setúbal (P  SETUBAL01)","Si","No","No",1],
["United Kingdom","Cranfield","Cranfield University (UK CRANFIE01)","No","Si","No",2],
["Czech","Brno","Vysoké Ucení Technické v Brne (CZ BRNO01)","Si","Si","No",2],
["Czech","Prague","Ceské Vysoké Uceni Technické v Praze (CZ PRAHA10)","Si","Si","Si",2],
["Romania","Braşov","Universitatea 'Transilvania' din Brasov (RO BRASOV01)","No","Si","No",4],
["Romania","Bucharest","Universitatea 'Politehnica' din Bucuresti (UPB) (RO BUCURES11)","Si","Si","Si",6],
["Romania","Galaţi","Universitatea 'Dunarea de Jos' din Galati (RO GALATI01)","Si","Si","Si",4],
["Sweden","Göteborg","Chalmers tekniska högskola (S  GOTEBOR02)","Si","Si","No",3],
["Sweden","Jönköping","Högskolan i Jonköping (S  JONKOPING01)","Si","Si","No",2],
["Sweden","Linköping","Linköpings universitet (S  LINKOPI01)","Si","Si","Si",6],
["Sweden","Luleå","Luleå tekniska universitet (S  LULEA01)","Si","Si","No",1],
["Sweden","Lund","Lunds universitet (S  LUND01)","Si","Si","No",2],
["Sweden","Stockholm","Kungliga Tekniska högskolan (KTH) (S  STOCKHO04)","Si","Si","No",10],
["Turkey","Istanbul","Istanbul Teknik Üniversitesi (TR ISTANBU04)","Si","Si","No",2],
["Turkey","Istanbul","Yildiz Teknik Universitesi (TR ISTANBU07)","Si","Si","Si",2]
]
