
//--------------------CITIES

export const FETCH_CITIES_INDEX_SUCCESS = 'FETCH_CITIES_INDEX_SUCCESS'
export const REQUESTING_CITIES_INDEX = 'REQUESTING_CITIES_INDEX'
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS'
export const REQUESTING_CITY = 'REQUESTING_CITY'
export const REQUESTING_UPDATE_MARKERS = 'REQUESTING_UPDATE_MARKERS'
export const UPDATE_MARKERS_SUCCESS = 'UPDATE_MARKERS_SUCCESS'

//--------------------CITIES END


//--------------------AUTH

export const REQUESTING_CREATE_USER = 'REQUESTING_CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'
export const REQUESTING_LOG_IN = 'REQUESTING_LOG_IN'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'

//--------------------AUTH END
