//--------------------CITIES

export const FETCH_CITIES_INDEX_SUCCESS = "FETCH_CITIES_INDEX_SUCCESS";
export const REQUESTING_CITIES_INDEX = "REQUESTING_CITIES_INDEX";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const REQUESTING_CITY = "REQUESTING_CITY";

//--------------------CITIES END

//--------------------COUNTRY

export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const REQUESTING_COUNTRY = "REQUESTING_COUNTRY";

//--------------------COUNTRY END

//--------------------COUNTRIES

export const FETCH_ALL_COUNTRIES_SUCCESS = "FETCH_ALL_COUNTRIES_SUCCESS";
export const REQUESTING_ALL_COUNTRIES = "REQUESTING_ALL_COUNTRIES";

//--------------------COUNTRIES END

//--------------------AUTH

export const SET_AUTH_USER = "SET_AUTH_USER";
export const JUST_LOGGED_IN = "JUST_LOGGED_IN";
export const USER_JUST_CREATED = "USER_JUST_CREATED";
export const SET_AUTH_USER_ERROR = "SET_AUTH_USER_ERROR";

//--------------------AUTH END

//--------------------PLACES

export const SAVING_PLACE = "SAVING_PLACE";
export const FETCHING_PLACES = "FETCHING_PLACES";
export const FETCHING_PLACES_SUCCESS = "FETCHING_PLACES_SUCCESS";
export const SAVING_PLACE_SUCCESS = "SAVING_PLACE_SUCCESS";
export const SAVING_PLACE_ERROR = "SAVING_PLACE_ERROR";

//--------------------PLACES END

//--------------------EVENTS

export const FETCHING_EVENTS = "FETCHING_EVENTS";
export const FETCHING_EVENTS_SUCCESS = "FETCHING_EVENTS_SUCCESS";
export const FETCHING_EVENT = "FETCHING_EVENT";
export const FETCHING_EVENT_SUCCESS = "FETCHING_EVENT_SUCCESS";

//--------------------EVENTS END
