
//--------------------CITIES

export const FETCH_CITIES_INDEX_SUCCESS = 'FETCH_CITIES_INDEX_SUCCESS'
export const REQUESTING_CITIES_INDEX = 'REQUESTING_CITIES_INDEX'
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS'
export const REQUESTING_CITY = 'REQUESTING_CITY'

//--------------------CITIES END


//--------------------AUTH

export const SET_AUTH_USER = 'SET_AUTH_USER'
export const JUST_LOGGED_IN = 'JUST_LOGGED_IN'
export const USER_JUST_CREATED = 'USER_JUST_CREATED'
export const SET_AUTH_USER_ERROR = 'SET_AUTH_USER_ERROR'

//--------------------AUTH END

//--------------------EXPERIENCES

export const SAVING_EXPERIENCE = 'SAVING_EXPERIENCE'
export const SAVING_EXPERIENCE_SUCCESS = 'SAVING_EXPERIENCE_SUCCESS'
export const SAVING_EXPERIENCE_ERROR = 'SAVING_EXPERIENCE_ERROR'

//--------------------EXPERIENCES END

//--------------------USER_MESSAGES

export const FETCH_USER_MESSAGES_SUCCESS = 'FETCH_USER_MESSAGES_SUCCESS'

//--------------------USER_MESSAGES END
