name: Build and Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REACT_APP_PROJECT_ID: ${{ github.ref_name == 'dev' && secrets.REACT_APP_PROJECT_ID_DEV || secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_API_KEY: ${{ github.ref_name == 'dev' && secrets.REACT_APP_API_KEY_DEV || secrets.REACT_APP_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{ github.ref_name == 'dev' && secrets.REACT_APP_AUTH_DOMAIN_DEV || secrets.REACT_APP_AUTH_DOMAIN }}
      REACT_APP_DATABASE_URL: ${{ github.ref_name == 'dev' && secrets.REACT_APP_DATABASE_URL_DEV || secrets.REACT_APP_DATABASE_URL }}
      REACT_APP_STORAGE_BUCKET: ${{ github.ref_name == 'dev' && secrets.REACT_APP_STORAGE_BUCKET_DEV || secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ github.ref_name == 'dev' && secrets.REACT_APP_MESSAGING_SENDER_ID_DEV || secrets.REACT_APP_MESSAGING_SENDER_ID }}
      REACT_APP_APP_ID: ${{ github.ref_name == 'dev' && secrets.REACT_APP_APP_ID_DEV || secrets.REACT_APP_APP_ID }}
      REACT_APP_MEASUREMENT_ID: ${{ github.ref_name == 'dev' && secrets.REACT_APP_MEASUREMENT_ID_DEV || secrets.REACT_APP_MEASUREMENT_ID }}
      REACT_APP_MAPS_API_KEY: ${{ secrets.REACT_APP_MAPS_API_KEY }}
      REACT_APP_PLACES_API_KEY: ${{ github.ref_name == 'dev' && secrets.REACT_APP_PLACES_API_KEY_DEV || secrets.REACT_APP_PLACES_API_KEY }}
      REACT_APP_MAPS_STYLE: ${{ secrets.REACT_APP_MAPS_STYLE }}
      GCP_SA_KEY_BASE_64: ${{ github.ref_name == 'dev' && secrets.GCP_SA_KEY_BASE_64_DEV || secrets.GCP_SA_KEY_BASE_64 }}
      CI: ""

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build
          path: build
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      # Because env context (environment variables) set at the job level are not directly accessible in the with or env fields of a step
      REACT_APP_PROJECT_ID: ${{ github.ref_name == 'dev' && secrets.REACT_APP_PROJECT_ID_DEV || secrets.REACT_APP_PROJECT_ID }}
      CI: ""
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0

      - name: Download Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: build
          path: build

      - name: Install functions dependencies
        run: npm i -D

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.4.0
        with:
          args: deploy --project ${{ env.REACT_APP_PROJECT_ID }}
        env:
          GCP_SA_KEY: ${{ env.GCP_SA_KEY_BASE_64 }}
