name: Deploy SityEx web app

on:
  push:
    branches:
      - dev
      - main

env:
      NEXT_PUBLIC_PROJECT_ID: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_PROJECT_ID_DEV || secrets.NEXT_PUBLIC_PROJECT_ID }}
      NEXT_PUBLIC_API_KEY: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_API_KEY_DEV || secrets.NEXT_PUBLIC_API_KEY }}
      NEXT_PUBLIC_AUTH_DOMAIN: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_AUTH_DOMAIN_DEV || secrets.NEXT_PUBLIC_AUTH_DOMAIN }}
      NEXT_PUBLIC_DATABASE_URL: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_DATABASE_URL_DEV || secrets.NEXT_PUBLIC_DATABASE_URL }}
      NEXT_PUBLIC_STORAGE_BUCKET: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_STORAGE_BUCKET_DEV || secrets.NEXT_PUBLIC_STORAGE_BUCKET }}
      NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID_DEV || secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_APP_ID: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_APP_ID_DEV || secrets.NEXT_PUBLIC_APP_ID }}
      NEXT_PUBLIC_MEASUREMENT_ID: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_MEASUREMENT_ID_DEV || secrets.NEXT_PUBLIC_MEASUREMENT_ID }}
      NEXT_PUBLIC_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }}
      NEXT_PUBLIC_PLACES_API_KEY: ${{ github.ref_name == 'dev' && secrets.NEXT_PUBLIC_PLACES_API_KEY_DEV || secrets.NEXT_PUBLIC_PLACES_API_KEY }}
      NEXT_PUBLIC_MAPS_STYLE: ${{ secrets.NEXT_PUBLIC_MAPS_STYLE }}
      NEXT_PUBLIC_MAPS_STREET_STYLE: ${{ secrets.NEXT_PUBLIC_MAPS_STREET_STYLE }}
      GCP_SA_KEY: ${{ github.ref_name == 'dev' && secrets.GCP_SA_KEY_BASE_64_DEV || secrets.GCP_SA_KEY_BASE_64 }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ github.ref_name == 'dev' && secrets.VERCEL_PROJECT_ID_DEV || secrets.VERCEL_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
      CI: ""

jobs:
  vercel:
    name: Vercel Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  firebase:
    name: Firebase Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set Up GCP Credentials
        run: |
          echo "${{ env.GCP_SA_KEY }}" | base64 -d > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Enable Firebase Experiments
        run: firebase experiments:enable webframeworks
      
      - name: Deploy to Firebase
        run: firebase deploy --project ${{ env.NEXT_PUBLIC_PROJECT_ID }}
